# This is a basic workflow to help you get started with Actions

name: System_Info_Emailer

# Controls when the workflow will run
on: workflow_dispatch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  system-info:
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment
      run: sudo apt-get update && sudo apt-get install -y rpm mailutils

    - name: Get system information
      run: |
        echo "OS Version:" > ~/sysinfo.txt
        cat /etc/os-release >> ~/sysinfo.txt

        echo -e "\nInstalled RPMs:" >> ~/sysinfo.txt
        rpm -qa >> ~/sysinfo.txt || echo "RPM not supported on this system" >> ~/sysinfo.txt

        echo -e "\nRoot ulimits:" >> ~/sysinfo.txt
        sudo bash -c 'ulimit -a' >> ~/sysinfo.txt

    - name: Email the report
      env:
        TO_EMAIL: wykjohn@gmail.com
      run: |
        uuencode sysinfo.txt ~/sysinfo.txt | mail -s "System Report" $TO_EMAIL
  
